---
apiVersion: v1
kind: ReplicationController
metadata:
  name: echo-rc
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: echo-app
    spec:
      containers:
      - name: echoserver
        image: gcr.io/google_containers/echoserver:1.0
        ports:
        - containerPort: 8080