---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
  labels:
    app: echo-app
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31302
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: echo-app