---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-app
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31402
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx-app